[project]
name = 'Renewable-Energy-Trading-Platform'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.energy-marketplace]
path = 'contracts/energy-marketplace.clar'
clarity_version = 2
epoch = 2.5

[contracts.energy-token]
path = 'contracts/energy-token.clar'
clarity_version = 2
epoch = 2.5

[contracts.smart-meter]
path = 'contracts/smart-meter.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
